import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./component/Navbar";

interface Props {
  children: JSX.Element;
  width: "fit-content" | "100%";
}

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Doctor Venu",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />

        {children}
      </body>
    </html>
  );
}
